#!/bin/bash

if [[ "$1" == "" ]]
    then
    echo "Usage: export SVN_PATH"
    exit
fi
    
SVN_DIR=$1

gs ()
{
    git svn clone $SVN_DIR${1} $2 
}

# With trunk/tags/branch
gst ()
{
    git svn clone $SVN_DIR${1} -T trunk -t tags -b branch $2 
}

# With trunk/tags/branches
gst-bs ()
{
    git svn clone $SVN_DIR${1} -T trunk -t tags -b branches $2 
}

sort_tags ()
{
    pushd $1
    shift
    for x in $@
    do
	git tag $x tags/$x
    done
    popd
}

sort_branches ()
{
    pushd $1
    shift
    for x in $@
    do
	git branch $x $x
    done
    popd
}

mkdir git
cd git

# msp430 libraries:
gst /boards/lib-fw/flash430 flash430
gst /boards/lib-fw/types msp430-types

for board in motor jointio pwm power
do
    gst /boards/${board}/firmware ${board}-fw
    # All pcbs have v1
    sort_tags ${board}-fw v1

    gst /boards/${board}/pcb ${board}-pcb

    gst-bs /boards/${board}/outline ${board}-outline
    # All boards have 2007
    sort_tags ${board}-outline 2007

    # Motor board doesn't have trunk/tags/branch structure
    if [[ "$board" != "motor" ]]
	then
	gst /boards/${board}/test-util ${board}-test
    else
	gs /boards/${board}/test-util ${board}-test
    fi

done

# Motor board
sort_tags motor-fw v0.1
sort_tags motor-pcb batch-00 prototype-00 prototype-01
sort_tags motor-test old v1

# JointIO
sort_tags jointio-pcb batch-00 build-00 v2
sort_tags jointio-outline 08-09

# PWM
sort_tags pwm-pcb batch-00 prototype-00 v0.9 v2

# Power
sort_tags power-fw pic-final
sort_tags power-pcb 0809_final_revision build-00 e5fix prototype-00 prototype-01
sort_tags power-outline 08-09
sort_tags power test-util old v1

gs /boards/slug/init-br slug-br

gst /boards/slug/pyenv pyenv
sort_tags pyenv 0.01  0.02  0.03  0.04  0.05  0.06  0.07  0.08  0.09  0.10  0.11  1.90
# todo: pyenv disttools + dummy

gst /boards/slug/i2c-msd i2c-msd
gst /boards/slug/c2py c2py

gst /boards/slug/outline slug-outline
sort_tags slug-outline 2007

gs /boards/slug/vision/robovis robovis

gst /boards/slug/xbout xbout
gs /boards/slug/utils/battmon battmon
gst /boards/slug/utils/flashb flashb
gs /boards/slug/utils/pinger xb-pinger

gs /web/drupal drupal
gs /web/planet planet

gst /web/srusers srusers
sort_tags srusers v0.01

gs /web/userman

gs /tools tools

gst-bs /Robo-IDE Robo-IDE
# TODO: Check branches ok
