#!/usr/bin/env python
import subprocess, git, os, externals, tempfile

URL_PREFIXES = [ "http://www.studentrobotics.org/svn",
                 "http://svn.studentrobotics.org",
                 "https://www.studentrobotics.org/svn",
                 "file:///home/rob/sr/dev/git-migration/svn" ]

def remove_prefix(url):
    for p in URL_PREFIXES:
        if url[:len(p)] == p:
            prefix = p
            break

    url = url[len(prefix):]
    return url

def extract_svn_revpath(commit):
    msg = commit.message

    for l in msg.splitlines():
        if "git-svn-id:" in l:
            break

    svn_line = l.strip()
    assert "git-svn-id: " in svn_line

    url = svn_line.split()[1]

    path = remove_prefix(url)

    rev = int(path[ path.find("@")+1: ])
    path = path[:path.find("@")]

    return (path, rev)

def find_rev():
    repo = git.Repo("./")
    chash = os.getenv( "GIT_COMMIT" )
    commit = repo.commit( chash )
    path, rev = extract_svn_revpath(commit)

    return rev

def translate_repo(url):
    "Translate the given subversion URL into a git repo"
    path = remove_prefix(url)
    
    for repo in externals.repos:
        if repo.svn_path == path[:len(repo.svn_path)]:
            p = path[len(repo.svn_path):]
            if p == "":
                p = "/"
            return (repo.path, p)
    assert False

def find_relative_loc(otherrepo):
    # WARNING: HARD-CODED
    print "WARNING: HARD CODED VALUE"
    mydir = "userman.git"

    my = mydir.count("/")
    #oy = otherrepo.count("/")
    loc = "../" * (my+1) + otherrepo
    print "Location:", loc
    return loc

def mangle_git_tree( basehash, exthash, path ):
    print "mangle_git_tree( basehash = '%s', exthash = '%s', path = '%s' )" % ( basehash, exthash, path )
    # Here lies git fu.
    if isinstance( path, str ):
        path = [x for x in path.split("/") if x !=  ""]

    tmpfd, treefname = tempfile.mkstemp()
    treef = os.fdopen(tmpfd, "w")

    # Get the current tree
    p = subprocess.Popen( args = "git ls-tree %s" % basehash,
                          stdout = subprocess.PIPE,
                          shell = True )
    r = p.communicate()
    p.wait()

    treeline = None
    if len(path) == 1:
        treeline = "160000 commit %s\t%s\n" % (exthash, path[0])

    for entry in r[0].splitlines():
        objperm, objtype, objhash, objname = entry.split()

        if objname == path[0]:
            "It's our tree line"

            if len(path) > 1:
                "We're a tree!"
                thash = mangle_git_tree( objhash, exthash, path[1:] )
                treeline = "040000 tree %s\t%s\n" % ( thash, path[0] )

            # Our line will be written after the loop
            continue

        treef.write( "%s\n" % entry )

    assert treeline != None

    treef.write( treeline )
    treef.close()

    print "Tree before:\n"
    subprocess.Popen( args = "git ls-tree %s" % basehash, shell = True ).wait()
    print
    print "Tree after:\n"
    subprocess.Popen( args = "cat %s" % treefname, shell = True ).wait()
    print

    # Make a tree object:
    print "Making new tree."
    p = subprocess.Popen( args = "cat %s | git mktree --missing" % treefname,
                          shell = True,
                          stdout = subprocess.PIPE )
    treeobj = p.communicate()[0].strip()
    p.wait()
    os.remove(treefname)

    print "Created tree object %s" % treeobj
    return treeobj



p = subprocess.Popen( args = "git svn show-externals",
                      stdout = subprocess.PIPE,
                      shell = True )

r = p.communicate()
p.wait()

newsub = not os.path.exists(".gitmodules")
gitmodules = None
cur_base_hash = os.getenv( "GIT_COMMIT" )

for l in r[0].splitlines():
    # Ignore externals lines that begin with #
    if len(l) == 0 or l[0] == '#':
        continue

    if gitmodules == None:
        gitmodules = open(".gitmodules", "w")

    print
    print "External:", l

    v = l.split()
    # We don't actually support specified revisions right now :-P
    assert len(v) == 2

    path, url = v
    rev = find_rev()

    if path[0] == "/":
        path = path[1:]

    reponame, repopath = translate_repo( url )

    # rev: The current subversion revision
    # path: The path that the external is checked out into
    # reponame: The external git repository (e.g. srusers.git)
    # repopath: The path within the original subversion external (e.g. /tags/v0.01)

    print "rev:", rev
    print "path:", path
    print "repopath:", repopath

    exthash = externals.find_chash( reponame, repopath, rev )
    print "hash:", exthash

    print
    print

    cur_base_hash = mangle_git_tree( cur_base_hash, exthash, path )

    # Read the tree object into the index 
    print "Reading tree into index."
    subprocess.Popen( args = "git read-tree %s" % cur_base_hash, shell = True ).wait()
    print "Checking out new tree."
    subprocess.Popen( args = "git checkout-index %s" % path, shell = True ).wait()    

    # Add to the gitmodules file:
    gitmodules.write( """[submodule "%s"]
	path = %s
	url = %s
""" % ( path, path, find_relative_loc(reponame) ) )

print
print
print
print
